#!/usr/bin/env python
"""Step 16 - analyse R4 (vote prediction, step 13) and analysis 1 (default swap, step 14). CPU; exploratory.

R4: accuracy of the persona's forced choice vs the recorded vote, against two baselines (party majority on that roll call;
    DW-NOMINATE prob > 0.5). Member-level accuracy on the member's persona entropy (step 1), on excess traditionalism
    (caricature, as in step 4), by party and by Congress. Choice uncertainty (binary entropy of p_yea) vs correctness.
Swap: entropy slope over persona position under each default (persona-only = step 7, plus D_qwen, D_prog, D_cons, D_hist),
    using the persona's own position measured without any default (step 7) so the x-axis is the same in every condition;
    position of each default alone; right - left gap for public figures under each default.
Output: out/votes_swap_summary.json, out/VOTES_SWAP_RESULTS.md, out/fig_votes_swap.png
Usage: python 16_analyze_votes_swap.py [--out out]
"""
import argparse, json
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
import common as cm

ap = argparse.ArgumentParser(); ap.add_argument("--out", default="out"); args = ap.parse_args()
OUT = cm.HERE / args.out; R = {}; f = lambda c: f"{c['est']:+.3f} [{c['ci95'][0]:+.3f}, {c['ci95'][1]:+.3f}], p = {c['p']:.3g}"
L = ["# R4 and default-swap results (generated by 16_analyze_votes_swap.py; exploratory, unadjusted p)", ""]

# ======================= R4 =======================
if (OUT / "vote_predictions.csv").exists():
    V = pd.read_csv(OUT / "vote_predictions.csv")
    V["pred"] = (V.p_yea > 0.5).astype(int); V["correct"] = (V.pred == V.yea).astype(int)
    V["party_pred"] = (V.party_yea_share > 0.5).astype(int); V["party_correct"] = (V.party_pred == V.yea).astype(int)
    V["dw_correct"] = (V.prob > 50).astype(int) if V.prob.max() > 1 else (V.prob > 0.5).astype(int)
    V["choice_entropy"] = -(V.p_yea * np.log2(V.p_yea.clip(1e-9)) + (1 - V.p_yea) * np.log2((1 - V.p_yea).clip(1e-9)))
    V["deviates_from_party"] = (V.yea != V.party_pred).astype(int)
    G = pd.read_csv(OUT / "member_generations.csv"); G = G[G.party.isin(["Democrat", "Republican"])]
    Mm = G.groupby(["icpsr", "congress"]).agg(entropy=("entropy64", "mean"), y=("y", "first"), dim1=("dim1", "first"), dim2=("dim2", "first"),
                                             era=("era", "first"), known=("known", "first")).reset_index()
    full = G.groupby(["icpsr", "congress"]).agg(y=("y", "first"), dim1=("dim1", "first"), dim2=("dim2", "first"), party=("party", "first"),
                                               era=("era", "first"), chamber=("chamber", "first")).reset_index()
    full["y_resid"] = cm.fit_cr1(full, "y ~ dim1 + dim2 + C(party) * C(era) + C(chamber)", "icpsr").resid
    V = V.merge(Mm[["icpsr", "congress", "entropy", "known"]], on=["icpsr", "congress"], how="left", validate="m:1").merge(
        full[["icpsr", "congress", "y_resid"]], on=["icpsr", "congress"], how="left", validate="m:1")
    V["rep"] = (V.party == "Republican").astype(int); V["rc"] = V.congress.astype(str) + V.chamber + V.rollnumber.astype(str)
    acc = dict(n_pairs=int(len(V)), members=int(V.icpsr.nunique()), roll_calls=int(V.rc.nunique()), persona=float(V.correct.mean()),
               party_majority=float(V.party_correct.mean()), dw_nominate=float(V.dw_correct.mean()), format_mass_median=float(V.format_mass.median()),
               persona_on_party_deviations=float(V[V.deviates_from_party == 1].correct.mean()), n_party_deviations=int(V.deviates_from_party.sum()))
    acc["by_party"] = V.groupby("party")[["correct", "party_correct", "dw_correct"]].mean().round(4).to_dict("index")
    acc["by_congress"] = V.groupby("congress")[["correct", "party_correct", "dw_correct"]].mean().round(4).to_dict("index")
    R4 = {"accuracy": acc}
    R4["correct_on_rep"] = cm.coef(cm.fit_cr1(V, "correct ~ rep + C(congress) + C(chamber)", "icpsr"), "rep")
    R4["correct_on_persona_entropy"] = cm.coef(cm.fit_cr1(V, "correct ~ entropy + rep + C(congress) + C(chamber)", "icpsr"), "entropy")
    R4["correct_on_caricature"] = cm.coef(cm.fit_cr1(V, "correct ~ y_resid + rep + C(congress) + C(chamber)", "icpsr"), "y_resid")
    R4["correct_on_choice_entropy"] = cm.coef(cm.fit_cr1(V, "correct ~ choice_entropy + C(rc)", "icpsr"), "choice_entropy")
    R4["persona_minus_party_baseline_by_rep"] = cm.coef(cm.fit_cr1(V.assign(gain=V.correct - V.party_correct), "gain ~ rep + C(congress) + C(chamber)", "icpsr"), "rep")
    R4["yea_bias"] = dict(predicted_yea=float(V.pred.mean()), actual_yea=float(V.yea.mean()),
                          by_party=V.groupby("party").agg(pred_yea=("pred", "mean"), actual_yea=("yea", "mean")).round(4).to_dict("index"))
    R4["tracks_party_position"] = {p: float(np.corrcoef(g.p_yea, g.party_yea_share)[0, 1]) for p, g in V.groupby("party")}
    R4["accuracy_by_party_and_party_side"] = {f"{p}|party_yea={s}": round(float(v), 4) for (p, s), v in V.groupby(["party", V.party_yea_share > 0.5]).correct.mean().items()}
    R["R4"] = R4
    L += [f"R4: {acc['n_pairs']} member x roll-call pairs ({acc['members']} members, {acc['roll_calls']} roll calls). Accuracy: persona {acc['persona']:.3f}, party majority {acc['party_majority']:.3f}, DW-NOMINATE {acc['dw_nominate']:.3f}; on the {acc['n_party_deviations']} votes against the party majority the persona is right {acc['persona_on_party_deviations']:.3f}. Format mass median {acc['format_mass_median']:.3f}.",
          f"- by party: {acc['by_party']}", f"- by Congress: {acc['by_congress']}",
          f"- correct ~ Republican: {f(R4['correct_on_rep'])}", f"- correct ~ persona entropy (open-ended, step 1): {f(R4['correct_on_persona_entropy'])}",
          f"- correct ~ caricature (excess traditionalism): {f(R4['correct_on_caricature'])}", f"- correct ~ choice entropy (roll-call FE): {f(R4['correct_on_choice_entropy'])}",
          f"- persona minus party baseline ~ Republican: {f(R4['persona_minus_party_baseline_by_rep'])}",
          f"- yea bias: {R4['yea_bias']}", f"- corr(p_yea, own party's yea share) by party: {R4['tracks_party_position']}",
          f"- accuracy by party and by the party's side: {R4['accuracy_by_party_and_party_side']}", ""]

# ======================= default swap =======================
if (OUT / "swap_generations.csv").exists():
    SP = pd.read_csv(OUT / "swap_personas.csv"); SG = pd.read_csv(OUT / "swap_generations.csv")
    T = pd.read_csv(OUT / "t1_personas.csv")
    base = T[["pid", "x", "y", "set", "side"]].rename(columns={"pid": "persona_pid", "x": "x0", "y": "y0"})
    T7 = pd.read_csv(OUT / "t1_generations.csv"); T7 = T7[(T7.rollout == 0) & T7.pid.isin(SP.persona_pid.dropna())]
    T7 = T7.assign(default="D_none", persona_pid=T7.pid)[["default", "persona_pid", "q", "entropy64"]]
    A = pd.concat([SG[SG.persona_pid.notna()][["default", "persona_pid", "q", "entropy64"]], T7]).merge(base, on="persona_pid", validate="m:1")
    Rs = {"default_alone_position": SP[SP.persona_pid.isna()].set_index("default")[["x", "y"]].round(3).to_dict("index")}
    for dft, g in A.groupby("default"):
        r = cm.fit_cr1(g, "entropy64 ~ x0 + y0 + C(q)", "persona_pid")
        gp = g[g.set == "P"].assign(right=lambda d: (d.side == "right").astype(int))
        rr = cm.fit_cr1(gp, "entropy64 ~ right + C(q)", "persona_pid")
        Rs[dft] = dict(slope_y0=cm.coef(r, "y0"), slope_x0=cm.coef(r, "x0"), figures_right_minus_left=cm.coef(rr, "right"), mean_entropy=float(g.entropy64.mean()))
    A["cons"] = (A["default"] == "D_cons").astype(int); A["prog"] = (A["default"] == "D_prog").astype(int)
    two = A[A["default"].isin(["D_prog", "D_cons"])]
    r = cm.fit_cr1(two.assign(cl=two.persona_pid), "entropy64 ~ y0 * cons + x0 * cons + C(q)", "cl")
    Rs["cons_minus_prog_slope_y0"] = cm.coef(r, "y0:cons"); Rs["cons_minus_prog_slope_x0"] = cm.coef(r, "x0:cons")
    R["swap"] = Rs
    L.append("Default swap: position of each default alone " + str(Rs["default_alone_position"]))
    for dft in ["D_none", "D_qwen", "D_prog", "D_cons", "D_hist"]:
        if dft in Rs:
            o = Rs[dft]; L.append(f"- {dft}: slope on persona y0 {f(o['slope_y0'])}; on x0 {f(o['slope_x0'])}; figures R-L {f(o['figures_right_minus_left'])}; mean entropy {o['mean_entropy']:.3f}")
    L.append(f"- conservative minus progressive default, slope on y0: {f(Rs['cons_minus_prog_slope_y0'])}; on x0: {f(Rs['cons_minus_prog_slope_x0'])}")
    L.append("H2 (anchor) predicts the slope flattens or reverses under D_cons; H1 (training) predicts the same sign under every default.")
(OUT / "votes_swap_summary.json").write_text(json.dumps(R, indent=1, default=float), encoding="utf-8")
(OUT / "VOTES_SWAP_RESULTS.md").write_text("\n".join(L) + "\n", encoding="utf-8"); print("\n".join(L))

fig, ax = plt.subplots(1, 2, figsize=(12, 4.2))
if "R4" in R:
    b = V.groupby(["congress", "party"]).agg(persona=("correct", "mean"), party_base=("party_correct", "mean")).reset_index()
    for p, c in (("Democrat", "tab:blue"), ("Republican", "tab:red")):
        q = b[b.party == p]; ax[0].plot(q.congress.map(cm.year_of), q.persona, "o-", color=c, label=f"persona, {p}")
        ax[0].plot(q.congress.map(cm.year_of), q.party_base, "s:", color=c, alpha=.6, label=f"party majority, {p}")
    ax[0].set_ylabel("accuracy on recorded votes"); ax[0].legend(fontsize=7); ax[0].set_title("R4: persona vote prediction vs party baseline", fontsize=10)
if "swap" in R:
    for dft, c in (("D_none", "k"), ("D_qwen", "gray"), ("D_prog", "tab:blue"), ("D_cons", "tab:red"), ("D_hist", "tab:green")):
        g = A[A["default"] == dft].groupby("persona_pid").agg(e=("entropy64", "mean"), y0=("y0", "first")).sort_values("y0")
        ax[1].plot(g.y0, g.e.rolling(9, center=True, min_periods=3).mean(), color=c, label=dft)
    ax[1].set_xlabel("persona social position without any default (step 7)"); ax[1].set_ylabel("entropy (rolling mean)"); ax[1].legend(fontsize=7)
    ax[1].set_title("Analysis 1: does the asymmetry follow the default?", fontsize=10)
fig.tight_layout(); fig.savefig(OUT / "fig_votes_swap.png", dpi=110)
