"""Fill OVERVIEW.template.md from ../release_core/RELEASE.json (numbers are never typed into the overview)."""
import json, re
from pathlib import Path
H = Path(__file__).resolve().parent
V = {k: v["value"] for k, v in json.loads((H.parent / "release_core" / "RELEASE.json").read_text(encoding="utf-8"))["values"].items()}
s = lambda x, d=2: f"{x:+.{d}f}".replace("-", "−")
u = lambda x, d=2: f"{x:.{d}f}".replace("-", "−")
ratios = [V[k] for k in ("s2_m2_ordinary_decade_ratio", "s2_m2_ordinary_era_ratio", "s2_m2_legislator_decade_ratio", "s2_m2_legislator_era_ratio")]
F = {"AUC_E": u(V["judge_auc_economic"]), "AUC_S": u(V["judge_auc_social"]), "Y1955": s(V["s2_yearswap_output_y1955"]), "Y2015": s(V["s2_yearswap_output_y2015"]),
     "ORD": s(V["s2_ordinary_output_1955_minus_2023"]), "M2MIN": f"{100 * min(ratios):.0f}", "M2MAX": f"{100 * max(ratios):.0f}",
     "EMP": f"{100 * V['s2_m2_employee_control_ratio']:.0f}".replace("-", "−"), "TONE_SD": u(V["s2_tone_ordinary_sd"]), "IDEO_SD": u(V["s2_ideology_ordinary_sd"]),
     "FORM_SD": u(V["s2_formality_ordinary_sd"]), "WVS_R": u(V["s2_wvs_person_corr"]), "CAL_YEAR": s(V["s3_calendar_internal_kim_per_year"], 3),
     "REAL_NP": s(V["s3_real_drift_internal_np1"], 3), "REP_RAW": u(V["s3_rep_corr_raw"]), "DW_UNITS": u(V["s4_yearswap_dw_units"]),
     "GAP": u(V["s4_party_gap_dw_2023"]), "REP_REAL": s(V["s4_real_rep_change_dw"]), "OUT_RATIO": f"{V['s4_output_ratio']:.1f}",
     "REP_CORR": u(V["s5_rep_corr_corrected"]), "BMIN": u(V["s5_baseline_corr_min"]), "BMAX": u(V["s5_baseline_corr_max"]),
     "ECON_OUT": s(V["s5_econ_output_ordinary_1955_minus_2023"])}
t = (H / "OVERVIEW.template.md").read_text(encoding="utf-8")
missing = set(re.findall(r"\{\{(\w+)\}\}", t)) - set(F)
assert not missing, f"unfilled keys: {missing}"
(H / "OVERVIEW.md").write_text("<!-- generated by fill_overview.py from release_core/RELEASE.json; edit OVERVIEW.template.md, not this file -->\n"
                               + re.sub(r"\{\{(\w+)\}\}", lambda m: F[m.group(1)], t), encoding="utf-8")
print("words:", len(t.split()))
